sudo: required
language: bash
services:
  - docker

env:
  - VERSION=2.17.0 LATEST=yes PROJECT=spryker

install: true

before_script:
  - env | sort
  - image="claranet/spryker-demoshop"
  - tag="${VERSION}${VARIANT:+-$VARIANT}"

script:
  - ./docker/run devel up -d
  - ./scripts/ci/run_tests.sh

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
      docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
      docker push $image:$tag;
      if [ "$LATEST" == "yes" ]; then
        docker tag $image:$tag $image:latest;
        docker push $image:latest;
      fi
    fi
